config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get :about,        to: 'static_pages#about'
  get :use_of_terms, to: 'static_pages#terms'
  get :signup,       to: 'users#new'
  get :login,        to: 'sessions#new'
  post :login,       to: 'sessions#create'
  delete :logout,    to: 'sessions#destroy'
  resources :users
  resources :recipes
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :name, presence: true, length: { maximum: 30 }
  validates :price,
            :numericality => {
              :only_interger => true,
              :greater_than_or_equal_to => 1,
              :less_than_or_equal_to => 3000
            },
            allow_nil: true
  validates :description, length: { maximum: 140 }
  validates :popularity,
            :numericality => {
              :only_interger => true,
              :greater_than_or_equal_to => 1,
              :less_than_or_equal_to => 5
            },
            allow_nil: true

  private
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
    before_action :logged_in_user
    before_action :correct_user, only: [:edit, :update]

    def new
      @recipe = Recipe.new
    end

    def show
      @recipe = Recipe.find(params[:id])
    end

    def create
        @recipe = current_user.recipes.build(recipe_params)
        if @recipe.save
          flash[:success] = "カスタムが登録されました！"
          redirect_to recipe_path(@recipe)
        else
          render 'recipes/new'
        end
    end

    def edit
      @recipe = Recipe.find(params[:id])
    end

    def update
      @recipe = Recipe.find(params[:id])
      if @recipe.update_attributes(recipe_params)
        flash[:success] = "カスタムが更新されました！"
        redirect_to @recipe
      else
        render 'edit'
      end
    end

  def destroy
    @recipe = Recipe.find(params[:id])
    if current_user.admin? || current_user?(@recipe.user)
      @recipe.destroy
      flash[:success] = "カスタムが削除されました"
      redirect_to request.referrer == user_url(@recipe.user) ? user_url(@recipe.user) : root_url
    else
      flash[:danger] = "他人のカスタムは削除できません"
      redirect_to root_url
    end
  end

  private

      def recipe_params
          params.require(:recipe).permit(:name, :price, :description, :drink, :popularity,)
      end

       def correct_user
         @recipe = current_user.recipes.find_by(id: params[:id])
         redirect_to root_url if @recipe.nil?
       end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_recipe.html.erb
<li id="recipe-<%= recipe.id %>">
  <%= link_to gravatar_for(recipe.user, size: 50), recipe.user %>
  <span class="name"><%= link_to recipe.name, recipe_path(recipe) %></span>
  <span class="price">値段(Tall)：<%= recipe.price %>円</span>
  <span class="description"><%= recipe.description %></span><br>
  <span class="drink"><%= recipe.drink %></span>
  <span class="popularity">おすすめ度:<%= recipe.popularity %></span><br>
  <span class="timestamp">
    <%= time_ago_in_words(recipe.created_at) %>前に投稿
  </span>
  <% if current_user.admin? || (current_user == recipe.user) %>
    <%= link_to "削除", recipe_path(recipe), method: :delete, data: { confirm: "本当に削除しますか？" } %>
  <% end %>
</li>

app/views/recipes/_recipe_form.html.erb
<%= form_with model: @recipe, local: true do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class = 'form-group'>
    <%= f.label :name %>　<span class="input-need">※必須</span>
    <%= f.text_field :name, class: 'form-control', id: 'recipe_name' %>
  </div>
　<div class = 'form-group'>
    <%= f.label :price %> [円]　<span class="input-unneed">※任意</span>
    <%= f.text_field :price, class: 'form-control', id: 'recipe_price' %>
  </div>
  <div class = 'form-group'>
    <%= f.label :description %>　<span class="input-unneed">※任意</span>
    <%= f.text_field :description, size: "60x4", class: 'form-control', id: 'recipe_description' %>
  </div>
  <div class = 'form-group'>
    <%= f.label :drink %> <span class="input-unneed">※任意</span>
    <%= f.text_field :drink, class: 'form-control', id: 'recipe_price' %>
  </div>
  <div class = 'form-group'>
    <%= f.label :popularity %> [1~5]　<span class="input-unneed">※任意</span>
    <%= f.text_field :popularity, class: 'form-control', id: 'recipe_popularity' %>
  </div>
  <%= f.submit nil, class: 'btn btn-primary' %>
<% end %>

app/views/recipes/edit.html.erb
<% provide(:title, "カスタム情報の編集") %>
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for(@recipe) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        <div class = 'form-group'>
          <%= f.label :name %>　<span class="input-need">※必須</span>
          <%= f.text_field :name, class: 'form-control', id: 'dish_name' %>
        </div>
        <div class = 'form-group'>
          <%= f.label :price %> [円] <span class="input-unneed">※任意</span>
          <%= f.text_field :price, class: 'form-control', id: 'recipe_price' %>
        </div>
        <div class = 'form-group'>
          <%= f.label :description %>　<span class="input-unneed">※任意</span>
          <%= f.text_field :description, size: "60x4", class: 'form-control', id: 'recipe_description' %>
        </div>
        <div class = 'form-group'>
          <%= f.label :drink %> <span class="input-unneed">※任意</span>
          <%= f.text_field :drink, class: 'form-control', id: 'recipe_drink' %>
        </div>
        <div class = 'form-group'>
          <%= f.label :popularity %> [1~5]　<span class="input-unneed">※任意</span>
          <%= f.text_field :popularity, class: 'form-control', id: 'recipe_popularity' %>
        </div>
        <%= f.submit "更新する", class: "btn btn-primary" %>
        <p></p>
        <%= link_to "料理を削除する", recipe_path(@recipe), method: :delete, data: { confirm: "本当にこのを削除してよろしいですか？" } %>
      <% end %>
    </div>
  </div>
</div>

app/views/recipes/new.html.erb
<% provide(:title, "カスタム登録") %>
<div class="container">
  <h1>カスタム登録</h1>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= render 'recipes/recipe_form' %>
    </div>
  </div>
</div>

app/views/recipes/show.html.erb
<% provide(:title, "#{@recipe.name}") %>
<div class="container">
  <div class="row">
    <div class='col-md-12'>
      <h2 class="recipe-name"><%= @recipe.name %></h2>
      <div class="change-recipe">
        <% if current_user == @recipe.user %>
          <%= link_to "カスタムを編集", edit_recipe_path(@recipe), class: 'edit-recipe' %>　
        <% end %>
        <% if current_user.admin? || (current_user == @recipe.user) %>
        　<%= link_to "削除", recipe_path(@recipe), method: :delete, class: 'delete-recipe', data: { confirm: "本当に削除しますか？" } %>
        <% end %>
      </div>
      <h4 class="recipe-price"><%= @recipe.price %></h4>
      <h4><%= @recipe.description %></h4>
      <h4 class="recipe-drink"><%= @recipe.drink %></h4>
      <div class="show-recipe-other-info">
        <div class="recipe-info">
          <h5>おすすめ度：</h5><h4><%= @recipe.popularity %></h4>
        </div>
      </div>
    </div>
  </div>
</div>